steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/smart-kiryana-backend:latest', '.']

# Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
  - 'run'
  - 'deploy'
  - 'smart-kiryana-backend'
  - '--image'
  - 'gcr.io/$PROJECT_ID/smart-kiryana-backend:latest'
  - '--region'
  - 'europe-west1'
  - '--platform'
  - 'managed'
  - '--allow-unauthenticated'

images:
- 'gcr.io/$PROJECT_ID/smart-kiryana-backend:latest'

options:
  logging: CLOUD_LOGGING_ONLY
