services:
  - type: web
    name: smart-store-backend
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
    envVars:
      - key: DB_MODE
        value: postgresql
      - key: FLASK_DEBUG
        value: "False"
      - key: DATABASE_URL
        fromDatabase:
          name: smart-store-db
          property: connectionString

databases:
  - name: smart-store-db
    plan: free
